
import java.beans.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Murilo
 */
public class Tela_Consulta1 extends javax.swing.JFrame {

    /**
     * private static final List<Filmes> lista = new ArrayList<>();
     *
     * public static List<Filmes> Listar() { return lista; } public static void
     * Adicionar(Filmes paciente) { lista.add(paciente); }
     *
     *
     * public static void Atualizar(){ String[] colunas = { "Nome", "Data de
     * Lançamento", "Categoria"}; DefaultTableModel tabelaModelo = new
     * DefaultTableModel(colunas, 0); List<Filmes> listaCompleta = new
     * ArrayList(); listaCompleta = Tela_Consulta.Listar();
     *
     *
     * for(int i=0; i<listaCompleta.size(); i++) {
     *
     * Filmes FilmeAtual = listaCompleta.get(i); String[] linha = {
     * FilmeAtual.getFilmeNome(), FilmeAtual.getFilmeData(),
     * FilmeAtual.getFilmeCategoria() }; tabelaModelo.addRow(linha); }
     * Tabela1.setModel(tabelaModelo);
    };*
     */

    public Tela_Consulta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Botao_Consulta = new javax.swing.JButton();
        Campo_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        String[] colunas = { "Nome", "Data de Lançamento", "Categoria"};
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
        Tabela1.setModel(tabelaModelo);
        jScrollPane1.setViewportView(Tabela1);

        Botao_Consulta.setText("Consultar");
        Botao_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Campo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botao_Consulta)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Campo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Botao_Consulta)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ConsultaActionPerformed
        java.sql.Statement st=null;
        ResultSet rs;
        Conexao2 con = new Conexao2();
        con.conectar();
        int ID = Integer.parseInt(Campo_ID.getText());
        String id = Campo_ID.getText();
        String sql = "SELECT * from filmes WHERE id =" + "'" + id + "'";

        try {
            st= Conexao2.conn.createStatement();

            Filmes1 filme = new Filmes1();

            rs = st.executeQuery(sql);
            //verificar se a consulta encontrou o funcionário com a matrícula informada
            if (rs.next()) { // se encontrou o funcionário, vamos carregar os dados
                filme.setFilmeNome(rs.getString("nome"));
                filme.setFilmeData(rs.getString("datalancamento"));
                filme.setFilmeCategoria(rs.getString("categoria"));
            } else {

            }
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar: " + ex.getMessage());

        }

        String[] colunas = {"Nome", "Data de Lançamento", "Categoria"};
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
        List<Filmes1> listaCompleta = new ArrayList();

        Filmes1 FilmeAtual = listaCompleta.get(ID);
        String[] linha = {
            FilmeAtual.getFilmeNome(),
            FilmeAtual.getFilmeData(),
            FilmeAtual.getFilmeCategoria()
        };
        tabelaModelo.addRow(linha);

        Tabela1.setModel(tabelaModelo);


    }//GEN-LAST:event_Botao_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Consulta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Consulta;
    private javax.swing.JTextField Campo_ID;
    public static final javax.swing.JTable Tabela1 = new javax.swing.JTable();
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
