/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programacao_oo_05;

/**
 *
 * @author Murilo
 */
public class Tela_Dois extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    Controle c =new Controle();
    public Tela_Dois() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        Botao_AumentaVolume = new javax.swing.JButton();
        Botao_DiminuiVolume = new javax.swing.JButton();
        Botao_Mudo = new javax.swing.JButton();
        Botao_Desmutar = new javax.swing.JButton();
        Botao_Play = new javax.swing.JButton();
        Botao_Pause = new javax.swing.JButton();
        Botao_FecharMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Volume: ");

        lblVolume.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblVolume.setText("0");

        Botao_AumentaVolume.setText("Aumentar volume");
        Botao_AumentaVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_AumentaVolumeActionPerformed(evt);
            }
        });

        Botao_DiminuiVolume.setText("Diminuir Volume");
        Botao_DiminuiVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_DiminuiVolumeActionPerformed(evt);
            }
        });

        Botao_Mudo.setText("Mutar");
        Botao_Mudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_MudoActionPerformed(evt);
            }
        });

        Botao_Desmutar.setText("Desmutar");
        Botao_Desmutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_DesmutarActionPerformed(evt);
            }
        });

        Botao_Play.setText("Play");
        Botao_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_PlayActionPerformed(evt);
            }
        });

        Botao_Pause.setText("Pause");
        Botao_Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_PauseActionPerformed(evt);
            }
        });

        Botao_FecharMenu.setText("Fechar Menu");
        Botao_FecharMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_FecharMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_FecharMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Botao_AumentaVolume)
                                    .addComponent(Botao_DiminuiVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botao_Desmutar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao_Mudo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Botao_Pause)
                            .addComponent(Botao_Play))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Botao_Play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botao_Pause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botao_FecharMenu)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_AumentaVolume)
                    .addComponent(Botao_Mudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_DiminuiVolume)
                    .addComponent(Botao_Desmutar))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_AumentaVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_AumentaVolumeActionPerformed
         lblVolume.setText(String.valueOf(c.maisVolume()));
    }//GEN-LAST:event_Botao_AumentaVolumeActionPerformed

    private void Botao_DiminuiVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_DiminuiVolumeActionPerformed
         lblVolume.setText(String.valueOf(c.menosVolume()));
    }//GEN-LAST:event_Botao_DiminuiVolumeActionPerformed

    private void Botao_MudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_MudoActionPerformed
        lblVolume.setText(c.ligarMudo());
    }//GEN-LAST:event_Botao_MudoActionPerformed

    private void Botao_DesmutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_DesmutarActionPerformed
        lblVolume.setText(String.valueOf(c.desligarMudo()));
    }//GEN-LAST:event_Botao_DesmutarActionPerformed

    private void Botao_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_PlayActionPerformed
       c.play();
    }//GEN-LAST:event_Botao_PlayActionPerformed

    private void Botao_PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_PauseActionPerformed
        c.pause();
    }//GEN-LAST:event_Botao_PauseActionPerformed

    private void Botao_FecharMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_FecharMenuActionPerformed
       
        c.fecharMenu();
    }//GEN-LAST:event_Botao_FecharMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Dois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Dois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Dois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Dois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Dois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_AumentaVolume;
    private javax.swing.JButton Botao_Desmutar;
    private javax.swing.JButton Botao_DiminuiVolume;
    private javax.swing.JButton Botao_FecharMenu;
    private javax.swing.JButton Botao_Mudo;
    private javax.swing.JButton Botao_Pause;
    private javax.swing.JButton Botao_Play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblVolume;
    // End of variables declaration//GEN-END:variables
}
