/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_teste_01;

import javax.swing.JOptionPane;

/**
 *
 * @author Murilo
 */
public class Tela_Central extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Central
     */
    ContaDAO cdao = new ContaDAO();
    public Tela_Central() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botao_SacarDepositar = new javax.swing.JButton();
        Botao_Excluir = new javax.swing.JButton();
        Botao_Transacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botao_SacarDepositar.setText("Sacar/ Depositar");
        Botao_SacarDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SacarDepositarActionPerformed(evt);
            }
        });

        Botao_Excluir.setText("Excluir");
        Botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ExcluirActionPerformed(evt);
            }
        });

        Botao_Transacao.setText("Transacao");
        Botao_Transacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_TransacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botao_SacarDepositar)
                    .addComponent(Botao_Excluir)
                    .addComponent(Botao_Transacao))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Botao_SacarDepositar)
                .addGap(18, 18, 18)
                .addComponent(Botao_Excluir)
                .addGap(18, 18, 18)
                .addComponent(Botao_Transacao)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_SacarDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SacarDepositarActionPerformed
        Tela_SacarDepositar tsd = new Tela_SacarDepositar();
        tsd.setVisible(true);
    }//GEN-LAST:event_Botao_SacarDepositarActionPerformed

    private void Botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ExcluirActionPerformed
      String r = JOptionPane.showInputDialog("Deseja Apagar essa conta? [S/N]");
        if(r.equals("S")){
          int i = cdao.obterId();
          cdao.excluir(i);
        }else{
            
        }
    }//GEN-LAST:event_Botao_ExcluirActionPerformed

    private void Botao_TransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_TransacaoActionPerformed
        Tela_Transacao tt = new Tela_Transacao();
        tt.setVisible(true);
    }//GEN-LAST:event_Botao_TransacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Central().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Excluir;
    private javax.swing.JButton Botao_SacarDepositar;
    private javax.swing.JButton Botao_Transacao;
    // End of variables declaration//GEN-END:variables
}
