/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_01;

import javax.swing.JOptionPane;

/**
 *
 * @author Murilo
 */
public class Tela_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    PacoteViagemDAO pvdao = new PacoteViagemDAO();
    TransporteDAO tdao = new TransporteDAO();
    HospedagemDAO hdao = new HospedagemDAO();
    hospedagem h;
    transporte t;
    pacoteViagem p = new pacoteViagem();
    float diariaHospedagem;
    float valorTransporte;
    int idT;
    int idH;
    public Tela_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JTextField();
        Botao_Hospedagem1 = new javax.swing.JButton();
        Botao_Hospedagem2 = new javax.swing.JButton();
        Botao_Hospedagem3 = new javax.swing.JButton();
        Botao_Hospedagem4 = new javax.swing.JButton();
        Botao_Hospedagem5 = new javax.swing.JButton();
        Botao_Hospedagem6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Campo_NumeroDias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Campo_Destino = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        Botao_Hospedagem1.setText("hospedagem 1");
        Botao_Hospedagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem1ActionPerformed(evt);
            }
        });

        Botao_Hospedagem2.setText("Hospedagem 2");
        Botao_Hospedagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem2ActionPerformed(evt);
            }
        });

        Botao_Hospedagem3.setText("HOSPEDAGEM3");
        Botao_Hospedagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem3ActionPerformed(evt);
            }
        });

        Botao_Hospedagem4.setText("Rodoviario");
        Botao_Hospedagem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem4ActionPerformed(evt);
            }
        });

        Botao_Hospedagem5.setText("Aereo");
        Botao_Hospedagem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem5ActionPerformed(evt);
            }
        });

        Botao_Hospedagem6.setText("Maritimo");
        Botao_Hospedagem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Hospedagem6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Hospedagens Disponiveis");

        jLabel3.setText("Metodos de Transporte");

        jLabel4.setText("Numero de Dias:");

        jLabel5.setText("Destino:");

        jButton1.setText("Realizar Compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Campo_NumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Campo_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton1)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Botao_Hospedagem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_Hospedagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(Botao_Hospedagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Botao_Hospedagem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_Hospedagem5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_Hospedagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campo_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Campo_NumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_Hospedagem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Hospedagem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Hospedagem3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_Hospedagem4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Hospedagem5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Hospedagem6)))
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_Hospedagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem1ActionPerformed
        try {
            h = hdao.escolhaHospedagem(1);
            diariaHospedagem = h.getValorDiaria();
            idH =h.getId();
           
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem1ActionPerformed

    private void Botao_Hospedagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem2ActionPerformed
        try {
            h = hdao.escolhaHospedagem(2);
            diariaHospedagem = h.getValorDiaria();
            idH =h.getId();
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem2ActionPerformed

    private void Botao_Hospedagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem3ActionPerformed
        try {
            h = hdao.escolhaHospedagem(3);
            diariaHospedagem = h.getValorDiaria();
            idH =h.getId();
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem3ActionPerformed

    private void Botao_Hospedagem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem4ActionPerformed
        try {
            t = tdao.escolhaTransporte(1);
            valorTransporte = t.getValor();
            idT = t.getId();
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem4ActionPerformed

    private void Botao_Hospedagem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem5ActionPerformed
        try {
            t = tdao.escolhaTransporte(2);
            valorTransporte = t.getValor();
            idT = t.getId();
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem5ActionPerformed

    private void Botao_Hospedagem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Hospedagem6ActionPerformed
        try {
            t = tdao.escolhaTransporte(3);
            valorTransporte = t.getValor();
            idT = t.getId();
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_Botao_Hospedagem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            
        p.setHospedagem_id(idH);
        p.setNomeHospede(Campo_Nome.getText());
        p.setqDias(Integer.parseInt(Campo_NumeroDias.getText()));
        p.setMargemLucro(1.10f);
        p.setTransporte_id(idT);
        p.setDestino(Campo_Destino.getText());
        p.setValorTotal((diariaHospedagem * p.getqDias() + valorTransporte) * p.getMargemLucro());
        JOptionPane.showMessageDialog(null, p.getValorTotal());
        pvdao.cadastrar(p);
         } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Hospedagem1;
    private javax.swing.JButton Botao_Hospedagem2;
    private javax.swing.JButton Botao_Hospedagem3;
    private javax.swing.JButton Botao_Hospedagem4;
    private javax.swing.JButton Botao_Hospedagem5;
    private javax.swing.JButton Botao_Hospedagem6;
    private javax.swing.JTextField Campo_Destino;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextField Campo_NumeroDias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
